Documentation:
  Enabled: false

AllCops:
  Exclude:
    - Gemfile
    - Gemfile.lock
    - spec/spec_helper.rb

Metrics/LineLength:
  Exclude:
    - 'spec/*.rb'
    - 'spec/features/*.rb'
  Max: 80

Metrics/BlockLength:
  Exclude:
    - 'spec/*.rb'
